# -*- coding: utf-8 -*-
"""IntroductionToQualcommAIHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgAUSoGwLhSzNCXwJ_-C1IkGgCfhHY22
"""

pip install qai-hub

!qai-hub configure --api_token <YOUR_API_TOKEN>

import qai_hub as hub
hub.get_devices()
